#!/usr/bin/python3
#    Copyright (C) 2018 by Bitonic B.V.
#
#    This file is part of Fireworks.
#
#    Fireworks is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    Fireworks is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with Fireworks. If not, see <http://www.gnu.org/licenses/>.

import logging

import configuration



def getFrontendModule(name):
    if name == 'qt':
        from frontend import frontend_qt
        return frontend_qt
    raise Exception('Unrecognized frontend name ' + name)


def getBackendModule(name):
    if name == 'lightningd':
        from backend import backend_lightningd
        return backend_lightningd
    elif name == 'lnd':
        from backend import backend_lnd
        return backend_lnd
    raise Exception('Unrecognized backend name ' + name)


config = configuration.Configuration()

logLevel = \
{
'critical': logging.CRITICAL,
'error'   : logging.ERROR,
'warning' : logging.WARNING,
'info'    : logging.INFO,
'debug'   : logging.DEBUG
}[config.getValue('core', 'loglevel')]
logging.basicConfig(
    format='%(asctime)s %(levelname)s: %(message)s',
    level=logLevel
    )

backendModule  = getBackendModule(config.getValue('modules', 'backend'))
frontendModule = getFrontendModule(config.getValue('modules', 'frontend'))

backend  = backendModule.Backend(config)
frontend = frontendModule.Frontend(config)

frontend.setBackend(backend)
backend.setFrontend(frontend)

frontend.run()

